# Generated by Django 4.1.4 on 2023-01-13 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=2, verbose_name='total')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='payments.payments', verbose_name='order')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.users', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.order_details', verbose_name='order')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.products', verbose_name='product')),
            ],
        ),
    ]
